### ISSUE TITLE
I am trying to run the command "python run.py --model bsds500 --in ./images/sample.png --out ./out.png" and I am getting the error:

### ISSUE THREAD

**Issue by chaitanyaspatil** [sniklaus/pytorch-hed#10]
Traceback (most recent call last):
  File "run.py", line 152, in <module>
    tenOutput = estimate(tenInput)
  File "run.py", line 135, in estimate
    netNetwork = Network().eval()
  File "run.py", line 95, in __init__
    self.load_state_dict({ strKey.replace('module', 'net'): tenWeight for strKey, tenWeight in torch.hub.load_state_dict_from_url(url='http://content.sniklaus.com/github/pytorch-hed/network-' + arguments_strModel + '.pytorch', file_name='hed-' + arguments_strModel).items() })
TypeError: load_state_dict_from_url() got an unexpected keyword argument 'file_name'

**Comment by sniklaus** [comment]
Update your PyTorch to version `1.6.0` or higher and let me know in case that didn't resolve the issue, thanks!
