### ISSUE TITLE
Using HED as a term of feature-based loss

### ISSUE THREAD

**Issue by MeLonJ10** [sniklaus/pytorch-hed#11]
Hi sniklaus,
Thanks very much for u excellent implementation.
There is a qusetion that I'd like to ask you for advice.
Have you ever used HED's feature map as a supervised term, just similar to VGG loss?
It would be greatly appreciated if you could offer me any suggestions!
Best,
Melon

**Comment by sniklaus** [comment]
I am afraid not. I worked on this implementation to do exactly this, but I never got around to do so.

**Comment by MeLonJ10** [comment]
Thank you so much for the quick reply!
