### ISSUE TITLE
RGB Normalization problem

### ISSUE THREAD

**Issue by linhl97** [sniklaus/pytorch-hed#15]
Hi, I noticed that in the forward function it normalizes the input as
``` 
tenBlue = (tenInput[:, 0:1, :, :] * 255.0) - 104.00698793
tenGreen = (tenInput[:, 1:2, :, :] * 255.0) - 116.66876762 
tenRed = (tenInput[:, 2:3, :, :] * 255.0) - 122.67891434
```
But when I noramlized it by ImageNet RGB mean[0.485, 0.456, 0.406] as follows:
``` 
tenBlue = tenInput[:, 0:1, :, :]  - 0.406
tenGreen = tenInput[:, 1:2, :, :] - 0.456
tenRed = tenInput[:, 2:3, :, :] - 0.485
```
The output become blurry:
![out2](https://user-images.githubusercontent.com/48047369/122718434-8781dd00-d29f-11eb-890d-af55b04eeb75.png)
I feel very confused about this cause it seems to be same normalization process

**Comment by sniklaus** [comment]
If you change the normalization like that, the value range will change from roughly [-128, 128] to [-0.5, 0.5]. The network is trained to operate on [-128, 128] though, so if you reduce the input range by a factor of 256 then the network behavior is ill constrained.

**Comment by linhl97** [comment]
> If you change the normalization like that, the value range will change from roughly [-128, 128] to [-0.5, 0.5]. The network is trained to operate on [-128, 128] though, so if you reduce the input range by a factor of 256 then the network behavior is ill constrained.

Thanks for quickly reply！
