### ISSUE TITLE
Multiple images as input

### ISSUE THREAD

**Issue by JamesLee789** [sniklaus/pytorch-hed#16]
Hello, @sniklaus Thanks for your contribution! Is there a way to generate edges from multiple images under a specific directory with your run.py? It seemed that your run.py can only process a single image as input so far. Thanks.

**Comment by sniklaus** [comment]
You can just change the following in `run.py` to load and process several images (I would recommend `glob`).

https://github.com/sniklaus/pytorch-hed/blob/5ef88c378053e0c865f4a60eb69db4c7f2714e8e/run.py#L149-L155
