### ISSUE TITLE
RuntimeError: shape '[1, 3, 320, 480]' is invalid for input of size 614400

### ISSUE THREAD

**Issue by tkamkb** [sniklaus/pytorch-hed#18]
`Traceback (most recent call last):
  File "run.py", line 153, in <module>
    tenOutput = estimate(tenInput)
  File "run.py", line 145, in estimate
    return netNetwork(tenInput.cuda().view(1, 3, intHeight, intWidth))[0, :, :, :].cpu()
RuntimeError: shape '[1, 3, 320, 480]' is invalid for input of size 614400
`
I tried to test my own image, but I got this error. The difference between sample.png and my own image.png is the bit depth. Mine is 32 bit depth.

**Comment by sniklaus** [comment]
`numpy.prod([1, 3, 320, 480]) == 460800` and `numpy.prod([1, 3, 320, 480]) == 614400`

You are trying to load an image with an alpha channel, try changing `estimate(tenInput)` to `estimate(tenInput[:, :3, :, :])`.

**Comment by tkamkb** [comment]
Thanks for your quick response! I try `tenOutput = estimate(tenInput[:3, :, :])` it works.
