### ISSUE TITLE
F-Score is terrible for individual images

### ISSUE THREAD

**Issue by Arka161** [sniklaus/pytorch-hed#19]
`Hello, 

I took images from the BSDS dataset, and individually analyzed the F-Scores. I observed that the result is pretty bad in general, and I am not sure what I'm doing wrong. I am suspecting a bug, but I'm not confident. 

**Image vs ground truth:** 
![image](https://user-images.githubusercontent.com/20723780/131149413-107ab8d8-a00d-4388-abff-d1091a532808.png)

**HED output:**
![image](https://user-images.githubusercontent.com/20723780/131149457-d42283e6-1e2f-40cc-b182-2f083ca0381b.png)

And of course, if the value of an individual cell is greater than 0.5, I round it off to 1 before estimating the F1 score. The image after rounding off looks like this:

![image](https://user-images.githubusercontent.com/20723780/131150555-c378e9dc-64f9-4069-8a4b-901e2e059669.png)

Then, I calculate the F-Score using the following code: 

Here, the `gt` is the groundtruth and the `pred` array is the prediction image from HED. 
```
tp = np.sum(pred[np.where(pred == 1)] == gt[np.where(pred == 1)])
fp = np.sum(pred[np.where(pred == 1)] != gt[np.where(pred == 1)])
precision = tp / (tp + fp)

# recall
fn = np.sum(pred[np.where(pred == 0)] != gt[np.where(pred == 0)])
recall = tp / (tp + fn)

# f-value
fvalue = 2 * precision * recall / (precision + recall)
```

I get a value (F1 score) of **0.1 to 0.2.** 
The paper and the Github descriptions state much higher values (>0.7). Can anyone guide me regarding what could be going wrong? Since I am using the same metric and the same score, it is a little tricky. 

Any help is appreciated.

**Comment by sniklaus** [comment]
I used https://github.com/zeakey/edgeval to get the ODS, and if you look into what it is doing then you'll find the following.

```matlab
imgs = dir(fullfile(edges_dir, '*.png')); imgs = {imgs.name};
for i = 1:length(imgs)
  if exist(fullfile(nms_dir, imgs{i}), 'file')
      continue; 
  end
  E = imread(fullfile(edges_dir, imgs{i})); E = single(E);
  E = E ./ max(E(:));
  [Ox,Oy] = gradient2(convTri(E,4));
  [Oxx,~] = gradient2(Ox); [Oxy,Oyy]=gradient2(Oy);
  O = mod(atan(Oyy.*sign(-Oxy)./(Oxx+1e-5)),pi);
  E = edgesNmsMex(E,O,1,5,1.01,4);
  imwrite(E, fullfile(nms_dir, imgs{i}));
end
param.resDir = nms_dir;
%% perform evaluation
[ODS,~,~,~,OIS,~,~,AP,R50] = edgesEvalDir( param );
```

As you see, it does NMS on the raw outputs first. For example, the following estimate.

![3063](https://user-images.githubusercontent.com/1238034/132143360-3fb1fa50-88f5-4b17-b45e-6cb7fb5418bd.png)

First gets processed using NMS such that the edges are much thinner.

![3063](https://user-images.githubusercontent.com/1238034/132143364-d0b31e49-5471-410a-a2ae-a4d3d364c908.png)
