### ISSUE TITLE
Where is the model file

### ISSUE THREAD

**Issue by 12314645** [sniklaus/pytorch-hed#24]

**Comment by sniklaus** [comment]
It gets downloaded in this line:

https://github.com/sniklaus/pytorch-hed/blob/732af4fbc5a6c44917ac3e428be043103e4701d7/run.py#L90

Let me know in case it is still unclear. :+1:

**Comment by 12314645** [comment]
> 

But，the url is Invalid 
![image](https://user-images.githubusercontent.com/95216119/211456894-7ec3aea5-d28c-4077-bd45-e1895f453918.png)

**Comment by 12314645** [comment]
Could you upload the model file，Thank!

**Comment by 12314645** [comment]
> It gets downloaded in the following line.
> 
> https://github.com/sniklaus/pytorch-hed/blob/732af4fbc5a6c44917ac3e428be043103e4701d7/run.py#L90
> 
> Let me know in case it is still unclear. 👍

I get it! Thank!
