### ISSUE TITLE
PyTorch HED

### ISSUE THREAD

**Issue by mariayuu** [sniklaus/pytorch-hed#25]
Hello!

I really liked the idea of finding the edges of images with  Holistically-Nested Edge Detection. But unfortunately, even on the sample.png image example, when I launch code "run.py" I have an error "option -f not recognized". I don't know how to solve this problem.

I also try to use reimplementation Pytorch Holistically-Nested Edge Detection with sample.png image example, I don’t get the same result as in the description, after running the code I get an image in gray shades and unlike contours.

I will be grateful for the answer!

**Comment by sniklaus** [comment]
Could you be more specific on how you launch "run.py"?

**Comment by mariayuu** [comment]
I tried to launch run.py file through Jupiter Notebook as a code and get error "option -f not recognized", also through the terminal (I have MacOS) and through IDLE but I keep getting an invalid syntax error. I am Python beginner. Please, tell me how to run file more correctly (command python run.py --model bsds500 --in ./images/sample.png --out ./out.png) and could I use online code editor for this? I really want to use this code.
Thank you for your reply!

**Comment by mariayuu** [comment]
I also try to use Google Colab, download there sample.png and run.py file and launch command:
!python run.py --model bsds500 --in ./sample.png --out ./out.png
But I get error RuntimeError: No CUDA GPUs are available.

**Comment by sniklaus** [comment]
Remove the two occurrences of `.cuda()` in `run.py` and try running it on Google Colab again.

**Comment by mariayuu** [comment]
Everything turned out great! Thanks a lot!
