### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by nywang2019** [sniklaus/pytorch-hed#4]
thank you for sharing.  How to test my own images with 512X512 size using your pretrained model?

**Comment by sniklaus** [comment]
Have you tried `python run.py --model bsds500 --in ./your-own-image.png --out ./out.png`?

**Comment by nywang2019** [comment]
i commented two assertion lines in run.py,  now it works with any image size.

**Comment by sniklaus** [comment]
I am happy to hear that and am closing this issue for now since it seems to work for you now. Feel free to reopen in case you run into any issues.
