### ISSUE TITLE
How to run on CPU?

### ISSUE THREAD

**Issue by purijs** [sniklaus/pytorch-hed#5]
Is there a way to run this on CPU?

**Comment by sniklaus** [comment]
Try removing `.cuda()` in the following segment and let me know in case that didn't work.

https://github.com/sniklaus/pytorch-hed/blob/92686ce1b29571cbfd9550fcbf7dc01d40f9a457/run.py#L131-L145

**Comment by purijs** [comment]
It works, but for some reason only for sample.png's width and height, If I comment out those lines, I get the following errors:

```
Traceback (most recent call last):
  File "run.py", line 152, in <module>
    tenOutput = estimate(tenInput)
  File "run.py", line 144, in estimate
    return netNetwork(tenInput.view(1, 3, intHeight, intWidth))[0, :, :, :].cpu()
RuntimeError: shape '[1, 3, 769, 1307]' is invalid for input of size 4020332

```

**Comment by sniklaus** [comment]
The image that you are trying to use has an alpha channel: `4 * 769 * 1307 == 4020332`

However, the input may only have three color channels. You can either remove the alpha channel from the image that you are trying to use, or explicitly exclude it during processing: `tenInput[0:3, :, :].view(1, 3, intHeight, intWidth`
