### ISSUE TITLE
problem of the pretrained model

### ISSUE THREAD

**Issue by 13462877152** [sniklaus/pytorch-hed#6]
HI ,good morning. So sorry to bother you .  There are something wrong with the pretrained network as follows .

deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 4922858 more bytes. The file might be corrupted.

![image](https://user-images.githubusercontent.com/33440801/88988078-6a03f780-d30a-11ea-9f85-850f1733ac16.png)

**Comment by sniklaus** [comment]
I just downloaded the model again and ran `run.py` without any issues. Could it be that the file got corrupted when you downloaded it on your end? Have you tried downloading the pre-trained model again?

**Comment by 13462877152** [comment]
Thank you very much for your help. I have tried downloading the pre-trained model again , and it's ok.  Thank you !
