### ISSUE TITLE
any further step suggested to obtain slim edges

### ISSUE THREAD

**Issue by tangeroo** [sniklaus/pytorch-hed#7]
Hi,
  Really appreciate your re-implement, do you have any suggestions for obtaining slimmer edges.
Thank you
Best

**Comment by sniklaus** [comment]
You could apply non-maximum suppression: https://en.wikipedia.org/wiki/Canny_edge_detector#Non-maximum_suppression

**Comment by tangeroo** [comment]
Thank you,
  this is my original image.
![image](https://user-images.githubusercontent.com/25971461/90844166-e16ef900-e395-11ea-9c4d-d24a915ad1a8.png)
  I tried opencv canny in this case. Followings are my hed  and after canny results. Canny seems not right for this, which obtained double edges and burrs. I am thinking maybe this hed method is still not fit for edge extraction although it really had good look edges. 
![image](https://user-images.githubusercontent.com/25971461/90844096-b4224b00-e395-11ea-9915-42aa652f4aae.png)
![image](https://user-images.githubusercontent.com/25971461/90844132-ce5c2900-e395-11ea-8843-ee50b908cf00.png)

**Comment by sniklaus** [comment]
I am afraid that just applying a Canny edge detector to the estimate from HED will not work. I just referenced the Canny edge detector article in my previous response because it is a popular non-max supression paradigm (which is what might work).

**Comment by tangeroo** [comment]
Yes, thanks a lot. Maybe I should try to integrate some other methods.

**Comment by zengxianyu** [comment]
maybe try opencv thresholding to binarize the edges
