### ISSUE TITLE
How can I adjust the level of detail of the output

### ISSUE THREAD

**Issue by feifeifeiliu** [sniklaus/pytorch-hed#8]
Hi, thank for your work! When I apply the network to some images, I found that the output is not fine-grained enough due to style gap and low resolution of source image. So how can I generate edge image with more detail? Change some hyperparameters?

**Comment by sniklaus** [comment]
My apologies, but this is just a reimplementation and I am not an author of the HED paper. It seems like your question may better be directed to the HED authors though. I would hence recommend you ask it here: https://github.com/s9xie/hed
